### ISSUE TITLE
Dependency free

### ISSUE THREAD

**Issue by djensen47** [convert-units/convert-units#103]
Have you considered making this library dependency free? For bundling it into front-end apps it would be nice for it to not have dependencies on external libraries.

P.S., great library, thanks for all the wonderful work

**Comment by djensen47** [comment]
Also, if you're interested in making this dependency free, I'm willing to put in a PR for the changes.

**Comment by jiminikiz** [comment]
Definitely sounds like a good idea

**Comment by djensen47** [comment]
I'll work on a PR soon-ish.

**Comment by Taar** [comment]
The project going forward will be dependency free.
