### ISSUE TITLE
Units that are industry specific as a plugin or similar

### ISSUE THREAD

**Issue by djensen47** [convert-units/convert-units#107]
Not everybody wants to convert specific gravity to balling to degrees plato ... but I do. Any thoughts on a plugin mechanism or at least a way to initialize my own units?

**Comment by elineopsommer** [comment]
@djensen47 you can also create a PR with those conversions, maybe there are others too which wants to convert that :)

**Comment by djensen47** [comment]
The problem with some industry units is that they clash with other industry units; even within the same industry:

1 beer barrel = 31 gallons
1 Bordeux barrel = 59 gallons
1 Burgundy barrel = 60 gallons

and so on; thus a plugin system might be nice.

Just a thought.

But to your point SG, Plato, and balling are actually standard and a PR could make sense for those. 😄

**Comment by dmbarry86** [comment]
@Taar I think this can be closed now with the recent changes as part of V3 which allow users to plugin their own custom units.
