### ISSUE TITLE
Types are missing from published module on NPM 

### ISSUE THREAD

**Issue by jimmykane** [convert-units/convert-units#108]
Hi, 

this https://github.com/ben-ng/convert-units/blob/master/lib/index.d.ts

is missing from the published module on NPM

**Comment by evanrs** [comment]
As a stopgap you can install from github `npm i -s  ben-ng/convert-units#d950cd1`

**Comment by edgarjrg** [comment]
This is still an issue with @2.3.3 - 2.3.4
