### ISSUE TITLE
hours and minutes

### ISSUE THREAD

**Issue by fcpauldiaz** [convert-units/convert-units#109]
is it possible to convert ms to hour: minutes? currently I only see the hour conversion (h)

**Comment by markusand** [comment]
Actually it's quite confusing to see 1.25h and having to interpret it as 1h15min. Same as having 1.8h

**Comment by nsaubi** [comment]
Here it even seems that 1.1 h is converted to 66.000000001 min for us.

**Comment by nsaubi** [comment]
Ok related to 1/10 values not being defined as a finite binary fraction
https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
