### ISSUE TITLE
Convert not found in angular test

### ISSUE THREAD

**Issue by elineopsommer** [convert-units/convert-units#111]
Running unit test for method which uses the convert, fails with message below:
`TypeError: undefined is not a constructor (evaluating 'convert_units_1.default(value)')`

Repro steps (with angular 6):  

1. ng new testapp
2. npm install convert-units

paste below code in `app.component.ts`
```
export class AppComponent {
  title = 'app';

  test = convert(12).from('mm').to('cm');

  constructor() {
    console.log(this.test);
  }
}
```

Running by `ng serve` will output the result, but running the tests will throw above error.

When importing this module in an angular 5, it won't even work when running `ng serve` and it throws the same error

**Comment by elineopsommer** [comment]
@jiminikiz any updates on this? this is really blocking

**Comment by vandammeb** [comment]
@jiminikiz having the same issue, any tips on how to get this working?

**Comment by Smiley01987** [comment]
@jiminikiz Any news on this?

**Comment by TryingToImprove** [comment]
How is it being imported? Normally you will need something like 

```
import convert from 'convert-units';
```

at the top of the _app.component.ts_ file.

**Comment by TryingToImprove** [comment]
For some reason this is failing;

Using 

```
import * as convert from "convert-units";
```

will work; see https://codesandbox.io/s/pm4o5mk48q -> _app/app.component.ts_

**Comment by goelinsights** [comment]
Are you injecting the dependency anywhere? With tree shaking, the library may be getting shaken out on compilation without the dependency being injected

**Comment by ntutchton** [comment]
A solution using InjectionTokens for others who might be running into this issue:
```
import { Inject, Injectable, InjectionToken } from '@angular/core';
import configureMeasurements, { length, speed } from 'convert-units';

converterConfig = {
length,
speed,
// can add custom unit definitions here
}

const CONVERTER_CONFIG = new InjectionToken('converter-config', {
  factory: () => () => ({ ...converterConfig })
});

const CONVERTER = new InjectionToken('converter', {
  factory: () => () => configureMeasurements
});

@Injectable({
  providedIn: 'root'
})
export class ConversionService {
  constructor(
    @Inject(CONVERTER) private converter,
    @Inject(CONVERTER_CONFIG) private config) {
      this.convert = converter(config);
 }

```

Then `ConversionService.convert(...)` can be called from angular components just as it is in the convert-units docs
