### ISSUE TITLE
Import only a certain type of units

### ISSUE THREAD

**Issue by hdodov** [convert-units/convert-units#131]
If I want to convert between units of mass, it would be cool to be able to include only that functionality in order to avoid bloating the codebase when developing an SPA.

For example:
```js
import { mass as convertMass } from 'convert-units';
```

**Comment by tanase-sebastian** [comment]
Hello,
I am too interested in this feature.
Anyways, this is a pretty handy lib.
Thanks !

**Comment by Taar** [comment]
This will be supported in version 3 of the library.
