### ISSUE TITLE
Bytes to KiloByte  wrong conversion

### ISSUE THREAD

**Issue by irfanbsse** [convert-units/convert-units#146]
**Example:**
`console.log(convert(1024).from('B').toBest())`

It will output this ` { val: 1, unit: 'KB', singular: 'Kilobyte', plural: 'Kilobytes' }`

According to goolge unit conversion
![Screenshot from 2019-05-13 13-17-27](https://user-images.githubusercontent.com/50095929/57606163-c6ea8500-7581-11e9-80d5-a6328e1d6212.png)
![Screenshot from 2019-05-13 13-17-52](https://user-images.githubusercontent.com/50095929/57606164-c6ea8500-7581-11e9-9f8c-813a4dcc1708.png)

Its using 1024 instead of 1000 for kilo byte and returning KB as a unit. Is there any option to change it to 1000.

**Comment by bstoots** [comment]
Hey there.  I ended up implementing the same conversion in my fork: https://github.com/bstoots/convert-units.  Feel free to check it out.

**Comment by ardelato** [comment]
Hello! 

This still seems to be an issue and is being used in the repo https://github.com/relative-ci/bundle-stats. 

I made an issue in that repo as well https://github.com/relative-ci/bundle-stats/issues/2619, but I am wondering if this an issue that is planned to be addressed?

**Comment by Taar** [comment]
@ardelato I submitted a PR for this #259 . Please verify that the contents of the PR would fix the issue. Thanks!

**Comment by ardelato** [comment]
@Taar looks like that fixed it! 

|Before|After|
|:---:|:---:|
|  ![Before](https://user-images.githubusercontent.com/22064420/188909251-977aa89b-2fe0-4db6-b742-dc0e5a0dbba1.png)     |    ![After](https://user-images.githubusercontent.com/22064420/188909247-fa5e0ef5-b0f3-448a-b64b-d4a2700eec54.png)   |

**Comment by Taar** [comment]
I've publish version 3.0.0-beta.5 to npm which includes this fix. Closing this issue.
