### ISSUE TITLE
Angular 7, Ionic 4?

### ISSUE THREAD

**Issue by argentini** [convert-units/convert-units#147]
Any idea how I can get this working in Ionic 4 or Angular 7? It compiles, but my component explodes when I try to use convert(). The error doesn't indicate convert() as the culprit - it says something about the component itself not being found.

**Comment by DukaN** [comment]
You should install (npm i convert-units) and import lib like that:
`import * as convertUnits from 'convert-units';`

And use it:
`convertUnits(source).from('m3').to('ft3');`

I hope it is helpful :)

**Comment by markamccorkle** [comment]
@argentini Did you ever get this working? Same issue here, just bombs out when you actually try to use convertUnits. Simply importing the component works fine until you actually try to use it.
(eg)
```
import * as convertUnits from 'convert-units';
getUnit {
    return convertUnits(1).from('g').to('mg'); 
}
```

**Comment by argentini** [comment]
I have not tried it. Converted my codebase to Xamarin.


M.


On Mon, Jan 20, 2020 at 8:19 AM, MM <notifications@github.com> wrote:
@argentini [https://github.com/argentini] Did you ever get this working? Same issue here, just bombs out when you actually try to use convertUnits. Simply importing the component works fine until you actually try to use it.
(eg)

import * as convertUnits from 'convert-units';
getUnit {
    return convertUnits(1).from('g').to('mg'); 
}

**Comment by drewmperkins** [comment]
Angular 9, this worked for me.

But I did have to add the following line to my polyfills.ts.  
(window as any).global = window;

Thanks DukaN


> You should install (npm i convert-units) and import lib like that:
> `import * as convertUnits from 'convert-units';`
> 
> And use it:
> `convertUnits(source).from('m3').to('ft3');`
> 
> I hope it is helpful :)
