### ISSUE TITLE
nautical mile and fathoms (#96) - Nautical Miles are in the github length.js file, but not in the npm published version

### ISSUE THREAD

**Issue by developer669** [convert-units/convert-units#150]
Hi, Thanks for the package very cool!
There is an issue according to commit **nautical mile and fathoms (#96)**  
You have added nautical mile to be supported according to github but it is not published on NPM , so when I install the npm package on angular 7 the nMi (nautical mile) is not there (not supported yet).
Can someone help me with this ?

**Comment by ColoradoFlyer** [comment]
It appears no one is maintaining this anymore -- I asked the same question a year ago.

We fixed it here by patching the file.  in our package.json file, we have:

  "scripts": {
    "patch": "patch -p1 < convert-units_Nmi.patch",
  }

And in convert-units_Nmi.patch we have:

--- ./node_modules/convert-units/lib/definitions/length.js	2018-01-04 11:44:46.000000000 -0700
+++ ./node_modules/convert-units/lib/definitions/length.js	2018-10-28 15:40:27.676000000 -0600
@@ -67,6 +67,13 @@
       plural: 'Miles'
     },
     to_anchor: 5280
+  },
+  nMi: {
+    name: {
+      singular: 'Nautical Mile',
+      plural: 'Nautical Miles',
+    },
+    to_anchor: 6076.12
   }
 };
