### ISSUE TITLE
toBest() conversion does not work with negative numbers

### ISSUE THREAD

**Issue by DerMika** [convert-units/convert-units#152]
Hi, 

I've noticed the `toBest()` method does not do what would be expected if you feed it a negative number.

I've built a repl to reproduce: https://repl.it/@DerMika/Reproduce-convert-units-issue

With a positive number: 

    convert(6596848).from('W').toBest()

The result will be converted to MW as expected:

    { val: 6.596848,  unit: 'MW',  singular: 'Megawatt',  plural: 'Megawatts' }

But with a negative number

    convert(6596848).from('W').toBest()

this is the result:
    
    { val: -6596848, unit: 'W', singular: 'Watt', plural: 'Watts' }

To be clear, I would expect -6.596848 MW.

**Comment by nsaubi** [comment]
And if I can add, when you do a convert toBest with the 0 value, it will return the smallest unit possible.
convert(0).from('s').toBest() // 0 ns

I would have expected to get the result in the to_anchor : 1 unit (here, in seconds) without having to tweak our code

**Comment by bohndthi** [comment]
Hi, is there any solution to this problem?
