### ISSUE TITLE
Please merge pull requests

### ISSUE THREAD

**Issue by makroxyz** [convert-units/convert-units#160]

**Comment by alvitawa** [comment]
I feel like at this point someone should just take over.

**Comment by Eomm** [comment]
I have revamped the project as [@eomm/convert-units](https://github.com/Eomm/convert-units#readme) and I will take care of this nice project.

I don't think `js-quantities` fits the same usage as this module

**Comment by Taar** [comment]
Reviewing PRs now! It's going to take me a while to get through everything so please be patient! If you have an outstanding PR, please merge it with the master branch and run ESLint, prettier, and the tests.
