### ISSUE TITLE
back and forth conversions eventually result to 0

### ISSUE THREAD

**Issue by sethdorris** [convert-units/convert-units#161]
Seems to be a rounding issue with the code that results in decreasing rounding all the way back to 0;

For instance

convert 4m to inches results in =157.48032inches
convert 157.48032inches back to meters results in 3.987799872390404m
convert 3.987799872390404m back to inches results in 118.11024inches

obviously this happens until you convert back and forth until you get a 0.

**Comment by maneetgoyal** [comment]
Not really observing the issue in the current `main` branch.

Tested via:

```
() => {
  let inMetres = 4;
  const data = [4];
  for (let i = 0; i < 100; i += 1) {
    const inInches = convert(inMetres).from('m').to('in');
    inMetres = convert(inInches).from('in').to('m');
    data.push(inMetres);
  }
  console.log(data);
}
```

```
[
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4,
      ... 1 more item
]
```

**Comment by dmbarry86** [comment]
I don't see this issue either. I have a small calculator app in one of my apps that uses this library and it seems to be just fine.

![image](https://user-images.githubusercontent.com/8976377/119330518-3077f080-bc7e-11eb-9287-ec509efcc4e3.png)

![image](https://user-images.githubusercontent.com/8976377/119330555-3968c200-bc7e-11eb-8a45-390273f939a6.png)

Maybe you could share some example code that demonstrates your issue @sethdorris?
