### ISSUE TITLE
named export

### ISSUE THREAD

**Issue by daniell0gda** [convert-units/convert-units#178]
Hello, I very like this module. Thank you for supporting it.

I am trying to make tests using 
- @open-wc
- karmajs
- stenciljs

Now I am facing issue with default export.

     Chrome Headless 90.0.4430.93 (Windows 10) ERROR
       Uncaught SyntaxError: The requested module '../../../../node_modules/convert-units/lib/index.js' does not provide an export      named 'default'
       at src/global/helper/units/unitsConversionHelper.ts:2:8

       SyntaxError: The requested module '../../../../node_modules/convert-units/lib/index.js' does not provide an export named 'default'
     Chrome Headless 90.0.4430.93 (Windows 10) ERROR: 'Error loading test file: /test/testing-stuff.e2e.ts'
     Chrome Headless 90.0.4430.93 (Windows 10) ERROR: 'SyntaxError: The requested module '../../../../node_modules/convert-units/lib/index.js' does not provide an export named 'default''

Here is my karma.config:
   

     const defaultSettings = require('@open-wc/testing-karma/testing-karma');
     const webpackMerge = require('webpack-merge');

     module.exports = config => {

    config.set(
        webpackMerge.merge(defaultSettings.createDefaultConfig(config), {
            files: [
                // allows running single tests with the --grep flag
                {
                    pattern: config.grep ? config.grep : 'test/**/*.e2e.ts',
                    type: 'module'
                },
                // 'node_modules/babel-polyfill/dist/polyfill.js'
            ],
            plugins: [
                // load plugin
                require.resolve('@open-wc/karma-esm'),

                // fallback: resolve any karma- plugins
                // 'karma-*',
            ],
            coverageIstanbulReporter: {
                thresholds: {
                    global: {
                        statements: 60,
                        branches: 60,
                        functions: 60,
                        lines: 60
                    }
                }
            },
            frameworks: ['esm', 'chai-dom', 'chai'],

            esm: {
                babel: false,
                nodeResolve: true,
                fileExtensions: ['.ts'],
                customBabelConfig: {
                    plugins: [
                        ['@babel/plugin-proposal-decorators', {legacy: true}],
                        '@babel/plugin-proposal-export-default-from'
                    ],
                    presets: [
                        '@babel/preset-typescript',
                    ],
                },
            },
            singleRun: false,
            autoWatch: true
        }),
    );

    return config;
};

Do you think this is possible?

**Comment by Taar** [comment]
My guess is that it's an issue with how the import is structured. I recommend importing the module using this syntax, `const convert = require('convert-units');`. [This post](https://stackoverflow.com/questions/29596714/new-es6-syntax-for-importing-commonjs-amd-modules-i-e-import-foo-require) should provide some insight into the issue and provide a few alternatives to my recommendation.

**Comment by panbanda** [comment]
I am seeing the same thing with my TS project.  I am just using various examples of the migration:

```ts
import configureMeasurements from 'convert-units'
import { allMeasures } from 'convert-units'

const convert = configureMeasurements(allMeasures)

export default convert
```

And I am getting these errors:
- Default export of the module has or is using private name 'Converter'.
- Exported variable 'convert' has or is using name 'Converter' from external module but cannot be named.

I think my scenario may be slightly different or maybe exporting the Converter from the package will handle it.

https://github.com/convert-units/convert-units/blob/main/src/convert.ts#L44

**Comment by Taar** [comment]
@panbanda Would you be able to provide your tsconfig, which version of `convert-units` you're using, and any other relevant information?

I have not been successful in reproducing this issue with the current beta release (`3.0.0-beta.1`).

**Comment by panbanda** [comment]
I tried re-creating the repo and realized the `beta.1` is now working for me.  I just realized I used the tag not the @beta.  Sorry bout that.

**Comment by panbanda** [comment]
Actually @Taar I was able to reproduce it again.  I made a repo repo:

https://github.com/panbanda/fix-convert-units-3.0-beta

If you look at `src/lib/convert.ts` there are the TS errors:

Default export of the module has or is using private name 'Converter'.
Exported variable 'convert' has or is using name 'Converter' from external module but cannot be named.

I am using

**Comment by Taar** [comment]
@panbanda Thanks for all the example! The repo didn't include a typescript version but that didn't seem to matter. I installed the latest version of typescript and was able to reproduce the issue. I've already merged the fix and published a fix under `3.0.0-beta.2`. Please let me know if the error goes away and I'll close this issue.

**Comment by panbanda** [comment]
Nice! You're fast. I'll check it out in a bit. Thanks

**Comment by panbanda** [comment]
Verified.  Good to go!
