### ISSUE TITLE
Adding the package with unpkg cdn

### ISSUE THREAD

**Issue by slim-abid** [convert-units/convert-units#187]
I was struggling with adding the package with unpkg cdn through 
`<script src="https://unpkg.com/convert-units@2.3.4/lib/index.js"></script>`
Is there a possibility to enhance this package capability to be added this way ?
This would really help!

**Comment by Taar** [comment]
From unpkg's website:

>For npm package authors, unpkg relieves the burden of publishing your code to a CDN in addition to the npm registry. All you need to do is include your UMD build in your npm package (not your repo, that's different!).

I plan to do exactly this for version 3 and beyond! Also while supporting other module systems as well.

**Comment by Taar** [comment]
Hey @slim-abid ! Would you be able to try `https://unpkg.com/convert-units@3.0.0-beta.0/lib/umd/index.js` and let me know if it works for your use case?

**Comment by mebeingken** [comment]
@Taar Thanks for your work on this!

I have convert-units (v2) working on the server side of a node project, but need to also use on the client.  

After installing beta2, I have loaded the script on my page:

`<script src="/js/convert-units/lib/umd/index.js"></script>`

But I don't know where to go from here...Can you provide any guidance?

**Comment by Taar** [comment]
> 
> 
> @Taar Thanks for your work on this!
> 
> I have convert-units (v2) working on the server side of a node project, but need to also use on the client.
> 
> After installing beta2, I have loaded the script on my page:
> 
> `<script src="/js/convert-units/lib/umd/index.js"></script>`
> 
> But I don't know where to go from here...Can you provide any guidance?

I recommend reading up on what [UMD](https://github.com/umdjs/umd) is and how it works. I also recommend using something like [webpack](https://webpack.js.org/) or [rollupjs](https://www.rollupjs.org/guide/en/) to help with managing dependencies used by your front-end code.

**Comment by slim-abid** [comment]
Thank you @Taar for the great work! and sorry also for the late response,
I will surely try it on my app since I've been implementing another solution last time due to time constraints.
