### ISSUE TITLE
v3.0.0: esm lib definitions/index.js does not import in browsers

### ISSUE THREAD

**Issue by Korkman** [convert-units/convert-units#200]
The import statements in definitions/index.js are missing the *.js file extension, which is required for browsers. If it doesn't break any use cases, please add them!

**Comment by Taar** [comment]
Thanks for reporting this, I'll look into the issue.

**Comment by patricksurry** [comment]
As a workaround I did `npm i @web/dev-server` and then `npx wds --node-resolve --watch --open` so I could follow imports like below in an HTML page without bundling via rollup or whatever:

```js
<script type="module">
        import configureMeasurements, {allMeasures} from './lib/esm/index';
        const convert = configureMeasurements(allMeasures);

        convert(29.92).from('inHg').to('hPa');
</script>
```

**Comment by Taar** [comment]
I am hoping that PR #256 fixes this. Could someone else help verify that it actually fixes the issue?
