### ISSUE TITLE
add shortcuts support

### ISSUE THREAD

**Issue by nsaubi-swi** [convert-units/convert-units#206]
Today when we want to have a shortcut for an unit, we just add it in the unit list.
E.g. : 
time.js : 
`day : {
   ...
}, d: {
  //same as day
}`
It would be nice to have a better way to add shortcuts to an unit, which should be accessible so we can display the information to the end user (using describe() by example)

**Comment by Taar** [comment]
A feature like this is implemented in the beta version by defining a custom measure or extending an existing measure. No more need to directly modify the source code. Please note that the documentation on this is still a work in progress. Though, feel free to keep any questions you have here about creating or modifying measures.
