### ISSUE TITLE
Automatically derive compound units?

### ISSUE THREAD

**Issue by patricksurry** [convert-units/convert-units#211]
Has anyone looked at supporting a simple algebra for compound units?

For example, once we know how to convert from feet => kilometers and hours => seconds, we can automatically work out how to convert from ft/sec => km/hour, and avoid implementing all those combinations separately.

Seems like it would require writing compound unit explicitly (or at least know that kph is an abbreviation for km / hour), with some simple expression parser that can deal with unit names, multiply, divide and exponent for dimensional analysis.  e.g. gravitational constant would have units "m^3 / kg / s^2"

**Comment by dmbarry86** [comment]
I'm not sure this would actually save that much code or improve the library. You would still need to add each of the definitions since the library would need to know and so the only real thing you save would be the one line where you define the conversion factor. It could actually end up increasing the footprint of the library with additional code that would be required for parsing mathematical operators and automatically fetching conversion factors.

**Comment by patricksurry** [comment]
I was imagining something like what [math.js units](https://mathjs.org/docs/datatypes/units.html) does.   e.g. once you had defined length units like {m, nm, km, ft, mi} and time units like {s, min, hr} then you wouldn't need explicit definitions for most of the speed units in speed.ts:  converting from m/s to mi/hr is calculated by dividing the conversion for m => mi by that from s => hr.   

that said, you might still want aliases for units (like mi/hr => mph and nm/hr => knot) and it would require some parsing of the unit strings which would add complexity

**Comment by Taar** [comment]
> I'm not sure this would actually save that much code or improve the library. You would still need to add each of the definitions since the library would need to know and so the only real thing you save would be the one line where you define the conversion factor. It could actually end up increasing the footprint of the library with additional code that would be required for parsing mathematical operators and automatically fetching conversion factors.

I agree with this. At this current moment, I don't want to add anymore complexity to the project.

> I was imagining something like what [math.js units](https://mathjs.org/docs/datatypes/units.html) does. e.g. once you had defined length units like {m, nm, km, ft, mi} and time units like {s, min, hr} then you wouldn't need explicit definitions for most of the speed units in speed.ts: converting from m/s to mi/hr is calculated by dividing the conversion for m => mi by that from s => hr.
> 
> that said, you might still want aliases for units (like mi/hr => mph and nm/hr => knot) and it would require some parsing of the unit strings which would add complexity

If that's something you need then wouldn't you just use `math.js`? I am missing something? Aliases are indirectly supported in the beta version by modifying the unit's definition or by using a mapper.
