### ISSUE TITLE
String not assignment to parameter of Type AllMeasureUnits

### ISSUE THREAD

**Issue by nbren007** [convert-units/convert-units#217]
I'm using convert(temp).from('C').to('F'); which works fine until I try and set the values dynamically.

I want my system variables to dictate the To unit, but I get the message: "string not assignment to parameter of Type AllMeasureUnits" so can't compile.

var toUnit = 'F';
var temp = 32; //actual value fetched from database.
var convertedTemp = convert(temp).from('C').to(toUnit);

Seems to me that this would be a fairly standard use case, any thoughts?

**Comment by addiks** [comment]
Hello, I am running into a very similar issue. When I try to import the type like this:
```
import allMeasures, { AllMeasuresUnits } from 'convert-units/definitions/all';
```
Then I get an error:
```
ERROR in ./public/js/lib/asd/foo.js
Module not found: Error: Can't resolve 'convert-units/definitions/all' in '/my-project/public/js/lib/widgets'
 @ ./public/js/lib/asd/foo.js 5:12-52
 @ ./public/js/lib/main.js
 @ multi ./public/js/lib/main.js
error Command failed with exit code 2.
```
This error does not occur with only the "allMeasures" import.
Does anybody know what could be causing this error?

Things would be a lot easier if the module would just allow string parameters, as crotwell suggested.
