### ISSUE TITLE
Cant convert from 'kg' to 't'

### ISSUE THREAD

**Issue by Mr-Jami** [convert-units/convert-units#220]
Hey,
I tried to convert 1000kg to tons but somehow I got 1.10231

Is there a reason why it is not supported to convert from kg to tons properly?

**Comment by Taar** [comment]
Could the issue be that you're converting [`kg`](https://github.com/convert-units/convert-units/blob/main/src/definitions/mass.ts#L30) to [`t`](https://github.com/convert-units/convert-units/blob/main/src/definitions/mass.ts#L61) but what you meant to do is to convert [`kg`](https://github.com/convert-units/convert-units/blob/main/src/definitions/mass.ts#L30) to [`mt`](https://github.com/convert-units/convert-units/blob/main/src/definitions/mass.ts#L37)? The difference is `t` belongs to the imperial system while `mt` (metric tonne) belongs to the metric system.

Here's the code I used:

```javascript
import configureMeasurements from 'convert-units';
import { allMeasures } from 'convert-units';

const convert = configureMeasurements(allMeasures);

console.log(convert(1000).from('kg').to('t'));
// 1.1023122100918887
console.log(convert(1000).from('kg').to('mt'));
// 1
```

If that's not the issue, please provide a code snippet! 😄
