### ISSUE TITLE
Rendering of units in Latex.

### ISSUE THREAD

**Issue by shaaandi** [convert-units/convert-units#227]
Hi there,
 Thanks, everyone for the work.
 
 I am using the latest beta version in a production app and we want to render the units in latex. 
 For example:
 `m3`   -->  `m³` 
 
 I am not able to find any other library right now and I also know the `convert-units` is more about conversion and not the rendering part. However, just want to know if there is any plan or anyone using any other solutions -- or I need to map them myself. 👍 
 
 
 Cheers,

**Comment by Taar** [comment]
I would like to keep the scope of this library to only converting units. Therefore, there is no plans to support a feature like this.
