### ISSUE TITLE
Integrating in Angular project leads to compiler warning 'CommonJS or  AMD dependencies can cause optimization bailouts'

### ISSUE THREAD

**Issue by Rajdeep97** [convert-units/convert-units#230]
I import into Angular component in this way:

`import * as convert from 'convert-units';`

Then use it by:
```
var from = 'deg';
let to = ''rad";
let converted = convert(control.value).from(from).to(to);
```

This lead to the compiler warning:

> 'CommonJS or AMD dependencies can cause optimization bailouts'

Any solution to this? Anyone else facing similar issue?

**Comment by Taar** [comment]
Going to close this as it's been a while. Please create a new issue if you're still experiencing issues.
