### ISSUE TITLE
Stackblitz fails to run a project using this package because the dependencies couldn't be resolved.

### ISSUE THREAD

**Issue by kenmorechalfant** [convert-units/convert-units#231]
Version: 
`2.3.4`

I am using this package in a project that I'm working on and I'm not having any issues locally but the project will not open in Stackblitz due to the error screenshotted below. 

Stackblitz error: 
![The dependencies for this project couldn't be resolved. This usually means that a dependency in your package.json is incorrect.](https://user-images.githubusercontent.com/4629022/151268510-72157fe8-64f5-4858-94b6-4d4e5cf5bab1.png)

I would like to be able link to my repo on Stackblitz for my portfolio. You can [open any public Github repo on Stackblitz](https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github) with a URL in this format: 
- `stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}` or
- `stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}/tree/{TAG|BRANCH|COMMIT}`

I created a separate branch to narrow down the issue and removed most of the dependencies. Then I added them back one by one, opening each commit in Stackblitz. It failed add soon as I added `convert-units` back. 

I would help fix this if I could but I'm at a loss. Thank you. 

- [Commit which fails on Stackblitz](https://stackblitz.com/github/kenmorechalfant/unit-converter-react/tree/82e9b89dbb96ff730b1ee1d039ca7f91917d4f69)
- [The commit](https://github.com/kenmorechalfant/unit-converter-react/commit/82e9b89dbb96ff730b1ee1d039ca7f91917d4f69)

**Comment by kenmorechalfant** [comment]
https://github.com/stackblitz/core/issues/1723

**Comment by Taar** [comment]
It's likely that the issue is that for version `2.3.4` the package.json file has the old repository url of [github.com/ben-ng/convert-units](https://github.com/ben-ng/convert-units). A new version could be published with the correct url but that doesn't really solve the issue for the earlier versions.
