### ISSUE TITLE
Extend Energy with MJ and GJ?

### ISSUE THREAD

**Issue by palo-bit** [convert-units/convert-units#235]
Hi there, 

would it be possible to extend energy units with MJ and GJ?
Currently there are  'Wh' | 'mWh' | 'kWh' | 'MWh' | 'GWh' | 'J' | 'kJ' where 1 GWh translates to 3,600,000,000 kJ

Many thanks and I am happy to do a PR for it, as it seems to be a simple change.

**Comment by Taar** [comment]
The beta version supports [creating custom systems and units](https://github.com/convert-units/convert-units#custom-measures) as well as [extending existing measures](https://github.com/convert-units/convert-units#extending-existing-measures). However, if you're using the latest production version `2.3.4`, then this is not possible. 

> Many thanks and I am happy to do a PR for it, as it seems to be a simple change.

PRs to add units to the beta version are always welcome.
