### ISSUE TITLE
Can't use certain units that exists in definitions

### ISSUE THREAD

**Issue by BurnedBySnow** [convert-units/convert-units#240]
The ones that I have tried that do not work are cl, dl and yd.
![image](https://user-images.githubusercontent.com/79046917/162213259-e5b951a3-9f9f-47e3-9d55-aa1a1445809e.png)

**Comment by Taar** [comment]
There's not a lot to go off of here. Can you provide an isolated code sample?

The code sample should contain any custom units/definitions and it should clearly show which definitions are being used.
