### ISSUE TITLE
Remove nautical miles and fathoms from imperial

### ISSUE THREAD

**Issue by davetapley** [convert-units/convert-units#248]
For reason give on #246 I'd like to propose that nautical miles and fathoms added on #96 be removed from the `imperial` system.

**Comment by Taar** [comment]
I'm open to cleaning up the systems/measures so that the sets are smaller. What approach do you think would work?

**Comment by davetapley** [comment]
How about this: Leave `imperial` and `metric` as is (they will remain a set of all corresponding definitions), but:

Create and create a new `us-common` system which includes all the units in _italics_ on [here](https://en.wikipedia.org/wiki/United_States_customary_units), where:
> Most common measures shown in italics

**Comment by davetapley** [comment]
I've just settled on ⬇️  for now, I'll do PR if a few others 👍🏻 this
```js
    .toBest({ system: unitSystem, exclude: ["nMi", "fathom", "ft-us"] });
```

**Comment by Taar** [comment]
Ok, thanks for the update :smile:
