### ISSUE TITLE
mph/kmh

### ISSUE THREAD

**Issue by ghost** [convert-units/convert-units#26]
I was not able to find speed units, would someone create speed units?

^punisher

**Comment by ben-ng** [comment]
Feel free to create these yourself too.

**Comment by webmasterkai** [comment]
Miles per hour is available with `m/h`. Kilometres per hour is available with `km/h`. I believe this issue can be closed.

**Comment by Skasi** [comment]
Miles per hour should be `mph` or `mi/h`.
`m/h` would be meters per hour.
