### ISSUE TITLE
How to use this in Vue.js?

### ISSUE THREAD

**Issue by Sjoerd82** [convert-units/convert-units#265]
I see that there are wrapper packages that wrap convert-units for use in Vue. If possible I prefer to directly import the package.
However, I can't get this to work. I try to import this within a single-file component (it's a PWA) so it the bundler can optimize by code splitting.

I hacked this until it ran:
```
require('convert-units')
require('convert-units/lib/definitions/volume')
import configureMeasurements from 'convert-units'
import volume from 'convert-units/lib/definitions/volume'
```
Except that I get this error
```
TypeError: convert is not a function
```
When I use it like this:
```
    created() {
        const convert = configureMeasurements({
            volume,
        })
        this.myUnits = convert().list('volume')
    },
```

Those `requires` are weird, I never before had to do this when importing a module somewhere.
I'm not happy with this approach and feel like I'm doing it wrong.

**Comment by pdwinkel** [comment]
Use the following (for release 3.0.0-beta.5):
```
import configureMeasurements, {volume} from 'convert-units'

const convert = configureMeasurements({volume})
```

**Comment by Sjoerd82** [comment]
Thanks. When posted I wasn't aware that there was a separate v3 beta version, I now moved to **3.0.0-beta.5**.

If you only want one measure, pdwinkels suggesion works:
```
import configureMeasurements, {volume} from 'convert-units'
const convert = configureMeasurements({volume})
const test = convert(1).from('m3').to('mm3')
```

If you want all measures, I found, based on the README, that in Vite4/Vue3, I need to import "all" like so:
```
import configureMeasurements from 'convert-units'
import allMeasures from 'convert-units/lib/esm/definitions'
const convert = configureMeasurements(allMeasures)
const testVol = convert(1).from('m3').to('mm3')
const testLen = convert(1).from('m').to('mm')
const testMas = convert(1).from('kg').to('mg')
```

I don't think it is yet possible to get some measurements, unless we import various measurement objects from 'convert-units' and merge them. Which is not a very big deal, but this is probably something that the mentioned treeshaking functionality is going to provide?

Perhaps @Taar could verify that the mentioned approaches above are indeed the recommended approaches, and confirm trreeshaking is on the horizon? The fact that "it works", doesn't always mean that is good code :-). This post may help future Vue/Vite users to quickly get convert-units up and running.

**Comment by Taar** [comment]
> If you want all measures, I found, based on the README, that in Vite4/Vue3, I need to import "all" like so:

The imports were not configured correctly for `3.0.0-beta.5`. Hopefully the next release will resolve this issue and properly support both `esm` and `cjs`.

> Perhaps @Taar could verify that the mentioned approaches above are indeed the recommended approaches, and confirm trreeshaking is on the horizon? The fact that "it works", doesn't always mean that is good code :-). This post may help future Vue/Vite users to quickly get convert-units up and running.

No those are not going to be the recommend approaches. `3.0.0-beta.5` and prior versions didn't correctly configure imports. The examples in the `README.md` on the `main` branch are the recommended way to import definitions. Those changes haven't been released yet as I am still working on testing them but hopefully soon (tm). So right now, do/use whatever works for your project.

> Edit. Also, and related to this. Some insight in how to add your custom measurements into this setup would be appreciated. I have created a "measure", which I can use standalone, but how do I add this to the convert function, created by configureMeasurements?

There is a section in the [README.md](https://github.com/convert-units/convert-units#custom-measures) that is my best attempt to explaining how to create and use custom measures. The `configureMeasurements` function is where you would pass the custom measure. The returned instance `convert` does not support updating the measures. If you want to change the measures, you'll need to call `configureMeasurements` again.
