### ISSUE TITLE
Uncaught TypeError: convert is not a function

### ISSUE THREAD

**Issue by b9techsrc** [convert-units/convert-units#278]
import configureMeasurements from 'convert-units';
import volume from 'convert-units/lib/definitions/volume';

const convert = configureMeasurements( {volume} );  

const test = convert(1).from('l').to('ml')

Not sure why I am getting this error. Using it exactly as described.

**Comment by Taar** [comment]
What version are you using?

**Comment by b9techsrc** [comment]
I assumed I was using 2.3.3 since I just did npm install and 2.3.3 is the latest. it turns out it was 2.3.4 not sure why. I uninstalled it and re-install 2.3.3. I thought that would fix it. Unfortunately, it didn't. Still seeing the same issue
