### ISSUE TITLE
global is not defined     at node_modules/lodash.support/index.js

### ISSUE THREAD

**Issue by YuvalLevi5** [convert-units/convert-units#279]
I am using Vue.js 3, and I'm importing the convert-units (version: "^2.3.4") library like this:
`import configureMeasurements, { volume } from 'convert-units'
const convert = configureMeasurements({ volume })`

However, I'm getting an error message that says:

"Uncaught ReferenceError: global is not defined
at node_modules/lodash.support/index.js (index.js:30:37)
at __require2 (chunk-WQG2LZMB.js?v=faeb624f:16:50)
at node_modules/lodash._basecreatecallback/index.js (index.js:12:15)
at __require2 (chunk-WQG2LZMB.js?v=faeb624f:16:50)
at node_modules/lodash.foreach/index.js (index.js:9:26)
at __require2 (chunk-WQG2LZMB.js?v=faeb624f:16:50)
at node_modules/convert-units/lib/index.js (index.js:3:12)
at __require2 (chunk-WQG2LZMB.js?v=faeb624f:16:50)
at index.js:304:18"

The error disappears when I comment out the import.

**Comment by Taar** [comment]
The documentation present in the `main` branch only applies to that code. If you're using version `2.3.4` then you need to look at the documentation for that version, which can be found [here](https://www.npmjs.com/package/convert-units/v/2.3.4).

**Comment by jiangming96** [comment]
I also encountered this problem, how did this problem finally solve? It's better to attach detailed steps, thanks

**Comment by YuvalLevi5** [comment]
> I also encountered this problem, how did this problem finally solve? It's better to attach detailed steps, thanks

I modified the way I import, like this:

`
  import configureMeasurements from 'convert-units';
  import current from 'convert-units/definitions/current';
  import energy from 'convert-units/definitions/energy';
  import power from 'convert-units/definitions/power';
  import voltage from 'convert-units/definitions/voltage';
  import volume from 'convert-units/definitions/volume';
  
  const convert = configureMeasurements({
   current,
   energy,
   power,
   voltage,
   volume
  });
`

**Comment by jiangming96** [comment]
> > I also encountered this problem, how did this problem finally solve? It's better to attach detailed steps, thanks
> 
> I modified the way I import, like this:
> 
> import configureMeasurements from 'convert-units'; import current from 'convert-units/definitions/current'; import energy from 'convert-units/definitions/energy'; import power from 'convert-units/definitions/power'; import voltage from 'convert-units/definitions/voltage'; import volume from 'convert-units/definitions/volume';
> 
> const convert = configureMeasurements({ current, energy, power, voltage, volume });

Thanks, I'll try it
