### ISSUE TITLE
Unable to use main branch with this Git repo as NPM dependency

### ISSUE THREAD

**Issue by ayan4m1** [convert-units/convert-units#280]
I'm trying to use the latest, unpublished version of convert-units as it has functionality I need added in.

It seems as if the package is incapable of being used in this fashion - I imagine it would need to dynamically build itself as a postinstall script or something similar.

Reproduction: https://codesandbox.io/s/damp-browser-eyfrwj?file=/src/App.js

Simple solution, if you don't mind, would just be publishing a beta6 of 3.0.0. If that's unwanted churn, would you mind if I looked into an alternative setup that allows the package to be used both from a Git repo and NPM package?

**Comment by Taar** [comment]
Are you referring to #264 ? One of the main features of version 3 is custom measures. The measures are just objects that hold data. Therefore, those objects can be changed to fit the applications needs if for example, a required unit that is not present in the defaults. 

```typescript
// Note: I don't have the time to test this at the moment but in theory something like this will work
import configureMeasurements, { Measure, Unit } from "convert-units";
import length, { LengthImperialUnits, LengthSystems, LengthUnits } from "convert-units/definitions/length";

type ModifiedLengthImperialUnits = LengthImperialUnits | 'mil';
const imperial: Record<ModifiedLengthImperialUnits, Unit> = {
  ...length.system.imperial,
  mil: {
    name: {
      singular: 'Mil',
      plural: 'Mils',
    },
    to_anchor: 1 / 12000,
  },
};
const modifiedLength: Measure<LengthSystems, LengthUnits | 'mil'> = {
  systems: {
    metric: length.systems.metric,
    imperial,
  }
  anchors: length.anchors,
};

const convert = configureMeasurements({
    length: modifiedLength,
});
```

**Comment by ayan4m1** [comment]
Yep, ok, thanks.
