### ISSUE TITLE
Inaccuracies in conversion between ft² and m²

### ISSUE THREAD

**Issue by mostation** [convert-units/convert-units#281]
Hey,
Conversion between the two are inaccurate

```
import configureMeasurements, { area } from 'convert-units';
this.convertArea = configureMeasurements({area});

this.convertArea(9280).from("m2").to("ft2") -> 99888.992 
```
The answer should be  `99889.0848`

The issue occurs since the ratio is `10.7639` instead of `10.76391` in [area.ts](https://github.com/convert-units/convert-units/blob/c211bb7a4cb28d4e743c593a418023e0c5032be1/src/definitions/area.ts#L105)

To anyone finding this and need a workaround, I did this:
```
    import measure from 'convert-units/lib/cjs/definitions/area';
    let areaMeasure = measure;
    areaMeasure.anchors.metric.imperial.ratio = 10.76391;
    areaMeasure.anchors.imperial.metric.ratio = 1 / 10.76391;
    this.convertArea = configureMeasurements({
      areaMeasure
    });
```

Cheers

**Comment by cooljeffro** [comment]
I've found the ```convert``` package gives more accurate results:

https://runkit.com/cooljeffro/6410fc050aca180008c0c74e
