### ISSUE TITLE
Unable to resolve type definitions

### ISSUE THREAD

**Issue by rawnly** [convert-units/convert-units#284]
Hello, this project seems to solve our needs at work. But I can't make this running properly.

I'm trying to run the following typescript code

```ts
import configureMeasurements from 'convert-units';
import allMeasures from 'convert-units/definitions/all';

const convert = configureMeasurements(allMeasures);
```

but what I get from my ide is : `Unable to resolve path to module "convert-units/definitions/all".`

I also tried the `@beta` and to install type definitions from `@types/convert-units` but nothing seems to work so far.

**Comment by jiblett1000** [comment]
@Rawnly I'm using beta. Try this. Works for me:

```ts
import configureMeasurements, {
allMeasures
} from "convert-units";
```

**Comment by Aslam97** [comment]
I was able to solve it using beta version

```js
import configureMeasurements from 'convert-units'
import mass from 'convert-units/definitions/mass'

const convert = configureMeasurements({ mass })
```

**Comment by Taar** [comment]
The imports were fixed with the most resent beta version.
