### ISSUE TITLE
Replace ts-ignore with ts-expect-error in the test file

### ISSUE THREAD

**Issue by farnaz-rashidi** [convert-units/convert-units#287]
Hi everyone 👋 ,

I, hereby, would like to propose replacing `ts-ignore` with `ts-expect-error` in [this test file](https://github.com/convert-units/convert-units/blob/main/src/__tests__/best.test.ts). 
Based on the TS official documentation, [it is recommened](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#ts-ignore-or-ts-expect-error) to use `ts-expect-error` insetad of `ts-ignore` if you are writing a test where you expect the type system to error and I believe that's the case here.
I already have a PR ready to be submitted, however, following your contribution guide, I am opening this issue for further discussion. Would love to hear your thoughts :)

Cheers,
Farnaz

**Comment by farnaz-rashidi** [comment]
Here it is:
https://github.com/convert-units/convert-units/pull/295

**Comment by Taar** [comment]
Merged
