### ISSUE TITLE
Assertion Functions for Units

### ISSUE THREAD

**Issue by bennycode** [convert-units/convert-units#292]
I like the `convert-units` library because of its strict typings, which prevent the usage of arbitrary strings. You cannot simply pass it any string which is great for a typed library:

<img width="576" alt="image" src="https://github.com/convert-units/convert-units/assets/469989/6814388f-9730-49db-b0e2-e88f237d505c">

To make things even better for developers like me, it would be awesome if the library exports an [assertion function](https://typescript.tv/glossary/#Assertion-Functions) (like `assertUnit`). Do you have any plans to add such feature in the future?

**Comment by Taar** [comment]
Adding in guard functions is something I am looking into adding in but I don't have an ETA as of right now.

**Comment by Taar** [comment]
Closing because it's a dup of #244
