### ISSUE TITLE
Add unit: temperature difference

### ISSUE THREAD

**Issue by jwir3** [convert-units/convert-units#293]
I'm not 100% sure how we would add this, but we should differentiate a value on a given temperature _scale_ from a _difference_ in temperature (i.e. a _change_ in temperature). For example:
```
convert(1).from('f').to('c') // Returns -17.2222, which is correct if we're talking about 1 deg F on the scale
convert(32).from('f').to('c') - convert(1).from('f').to('c) // Returns -17.2222, but I would expect -0.555556 (i.e. the same as convert(32-1).from('f').to('c')
```

I suspect this somehow has to be a different unit.

**Comment by Taar** [comment]
The conversions are meant to be simple and straight forward. They also return a `number` which don't hold any information about the units. IMO, sounds like you need a completely different system than what this project can offer.
