### ISSUE TITLE
Implement new custom unit: galUK

### ISSUE THREAD

**Issue by Krister-Johansson** [convert-units/convert-units#294]
I tried to add galUK, but I didn't manage to follow the documentation, or I'm misunderstanding the docs.
I don't get any error but when I try to convert from let's say L or m3 to galUK or the other way around.
I got the wrong answer. What am I missing?

const extendedVolume: Measure<VolumeSystems, NewVolumeUnits> = {
  systems: {
    metric: {
      ...volume.systems.metric,
    },
    imperial: {
      ...volume.systems.imperial,
      galUK: {
        name: {
          singular: 'Imperial gallon',
          plural: 'Imperial gallons',
        },
        to_anchor: 4.54609,
      },
    },
  },
  anchors: {
    ...volume.anchors,
    metric: {
      ...volume.anchors.metric,
      imperial: {
        ratio: 0.219969,
      },
    },
    imperial: {
      ...volume.anchors.imperial,
      metric: {
        ratio: 1 / 0.219969,
      },
    },
  },
};

**Comment by Taar** [comment]
Can you provide examples of the values you are getting vs what you're expecting?
