### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by visusnet** [convert-units/convert-units#297]
Hi @Taar,

will there be a new release? The latest beta version is more than a year old and the latest non-beta version is more than 6 years old. It looks like there is still development happening (e.g. Ws and Wm have been added) but there are no more new versions. Is this project almost dead?

**Comment by Taar** [comment]
Comments like these don't add any value and are quite annoying, especially the "Is this project almost dead?" part. If you're unhappy with the pace then fork and publish your own package.
