### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by 12Jeef** [convert-units/convert-units#301]
I was just wondering how I could get this library working for the browser. I don't use webpack nor rollup, so I don't have any easy way to just import this module. I am using ES6 imports, and the project I am working on is very large, so any restructuring such as changing from ES6 syntax to CommonJS syntax would be really difficult. Is there any way for me to use this in the browser?

**Comment by Taar** [comment]
The latest beta version supports ES Modules which should cover your use case. If you end up trying it and run into issues please open a new issue.
