### ISSUE TITLE
Feature request: option for `toBest` to always return a valid result

### ISSUE THREAD

**Issue by mikethemerry** [convert-units/convert-units#307]
Currently, the following returns a null value

```
const convert = configureMeasurements(allMeasures);
const result = convert(4e-10).from("kg").toBest();
console.log(result); // null
```
I would expect some way to guarantee a result, even if it's not as good as hoped, with maybe a flag, e.g., `.toBest({extendLimits:True})` which would return something like 

```
{
  "plural": "Micrograms",
  "singular": "Microgram",
  "unit": "mcg",
  "val": 0.4000000000000001,
}
```
Which would be the best unit possible.

Secondly, I would expect a `convert(0)` to be safe with `toBest()`, returning just the same unit

```
const resultZero = convert(0).from("kg").toBest();
console.log(result);
{
  "plural": "Kilograms",
  "singular": "Kilogram",
  "unit": "kg",
  "val": 0,
}
```

The value that this gives is that as long as `convert().from()` is properly formed, `toBest()` will always return a consistent structure with sensible results. At the moment, I need to do a extra checking prior to use to get the desired behaviour.

**Comment by Taar** [comment]
Pull request #313 resolves this issue

**Comment by mikethemerry** [comment]
Thank you @Taar !
