### ISSUE TITLE
Overhaul digital measure

### ISSUE THREAD

**Issue by Taar** [convert-units/convert-units#317]
Pull request #316 is meant to fix the digital units and resolve #125 . I'm hoping that someone has the time to look over the pull request before I merge and let me know what they think.

Note that the pull request will introduce breaking changes as it renames units and systems.

References:
- https://en.m.wikipedia.org/wiki/Kilobyte
- https://en.m.wikipedia.org/wiki/Byte
- https://en.m.wikipedia.org/wiki/Bit

**Comment by vxow** [comment]
When can it be published?

**Comment by Taar** [comment]
Created a release just moments ago :smile:
