### ISSUE TITLE
Adding conversion function for specific quantities

### ISSUE THREAD

**Issue by mitja-p** [convert-units/convert-units#322]
Hi!

Would be possible to add a conversion function which would avoid parsing and measure lookup? Something in the sense of:
var fn = ConvertFn('mL', 'L');
fn(1000); // 1
fn(100); // 0.1

I have a situation where I need to convert 10000+ points to a new unit. In best situation each point should require one function call that would then only do arithmetic operations (no function calls within this function for performance reasons). 

Part of the solution should also be a way to avoid transform function for system anchors. Maybe in the same way as for measures (to_anchor, anchor_shift). One system should in this case be the anchor system. Or maybe 3 params shift_before, ratio, shift_after.

**Comment by mitja-p** [comment]
Here is a quick draft of the code:
```
var converter = configMeasurements({...})

function convertFn(from, to) {
  var c = converter();
  var dest = c.getUnit(to);
  var origin = c.getUnit(from);
  // Don't change the value if origin and destination are the same
  if (origin.abbr === dest.abbr) {
    return this.val;
  }
  // You can't go from liquid to mass, for example
  if (dest.measure != origin.measure) {
    throw new Error('Cannot convert incompatible measures of ' + dest.measure + ' and ' + origin.measure);
  }

  var sysanchor = { ratio: 1, offset: 0 };
  if (origin.system != dest.system) {
    const measure = c.measureData[origin.measure];
    const anchors = measure.anchors;
    const anchorOrigin = anchors[origin.system];
    if (origin.system != dest.system)
      sysanchor = { ratio: anchorOrigin[dest.system].ratio || 0, offset: anchorOrigin[dest.system].offset || 0 };
  }
  var origunit = { to_anchor: origin.unit.to_anchor, anchor_shift: origin.unit.anchor_shift || 0 };
  var destunit = { to_anchor: dest.unit.to_anchor, anchor_shift: dest.unit.anchor_shift || 0 };
  // Convert from source to anchor inside the system
  return (val) => {
    let result = val * origunit.to_anchor - origunit.anchor_shift;
    // Convert from system to system
    result = result * sysanchor.ratio + sysanchor.offset;
    // Convert from anchor to dest inside the system
    result = (result + destunit.anchor_shift) / destunit.to_anchor;
    return result;
  };
}
```

BTW performance wise it would be also nice if you wouldn't always search through all units but have a lookup list of units. So lookup['C'] would immediately return the data for unit C for temperature for example.

**Comment by Taar** [comment]
While performance is important, I don't think this library's goal aligns with this particular use case. I'm also not very keen on trying to change or append to the API to allow for this use case either. I also have a hard time believing that modifying this library to become extremely performant is going to solve your specific problem. If execution speed is a large concern then I wouldn't recommend using this library or even JavaScript to be frank. 

While function calls do have overhead, I don't think reducing function calls is going to give you the performance improvement that you're looking for. I wouldn't say JavaScript is the slowest language out there but it definitely isn't as quick at executing code as some other languages or as well equipped for this use case as other ecosystems are.

However, I definitely agree that faster look up of configured units would be a nice improvement and I've already been looking into a few ways to do that.
