### ISSUE TITLE
After update from beta6 to beta7 import for allMeasures broke

### ISSUE THREAD

**Issue by skatterwe** [convert-units/convert-units#332]
We have a very basic service that imports your convert-units utilities. 

After an update from `3.0.0-beta.6` to `3.0.0-beta.7`. The import statement for the definitions failed.

Our code in version `3.0.0-beta.6`:
```
import { Injectable } from '@angular/core';
import configureMeasurements from 'convert-units';
import allMeasures from 'convert-units/definitions/all';

...

@Injectable({
  providedIn: 'root',
})
export class EnvironmentalParametersService {
  convert: any;

  constructor() {
    this.convert = configureMeasurements(allMeasures);
  }
 ...
}
```

Error we got: `TS2307: Cannot find module convert-units/definitions/all or its corresponding type declarations.`

Code change needed with version `3.0.0-beta.7`:
```
import { Injectable } from '@angular/core';
import configureMeasurements from 'convert-units';
import allMeasures from 'convert-units/lib/esm/definitions/all'; // <- only importing it directly from the lib path helped

...

@Injectable({
  providedIn: 'root',
})
export class EnvironmentalParametersService {
  convert: any;

  constructor() {
    this.convert = configureMeasurements(allMeasures);
  }
 ...
}
```

**Comment by skatterwe** [comment]
By the looks that only satisfied the typescript compiler, but when trying to run the application we now get the following error:
`Module not found: Error: Package path ./lib/esm/definitions/all is not exported from package .../node_modules/convert-units (see exports field in .../node_modules/convert-units/package.json)`

**Comment by Taar** [comment]
Hey thanks for create an issue! I created a small vite project to help narrow down the issue

Contents of the `main.ts` file:
```ts
import configureMeasurements from 'convert-units';
import allMeasures from 'convert-units/definitions/all';

const convert = configureMeasurements(allMeasures);

console.log(convert(1000).from('mm').to('cm'));
``` 

and the following `tsconfig.json` (Typescript v5.5.4):

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true
  },
  "include": ["src"]
}
```

My editor doesn't report any issues and the code runs without issue.

![image](https://github.com/user-attachments/assets/36616790-5448-48c7-bc2d-b11b35053809)

And if I ran `tsc` like `npx tsc` or `npx tsc -p tsconfig.json` it doesn't produce any errors.

However, if I run it like so `npx tsc src/main.ts` I get the following errors:

```
node_modules/convert-units/lib/cjs/convert.d.ts:37:54 - error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

37 export type UnitCache<TMeasures, TSystems, TUnits> = Map<string, {
                                                        ~~~

src/main.ts:2:25 - error TS2307: Cannot find module 'convert-units/definitions/all' or its corresponding type declarations.
  There are types at '/home/taar/git/convert-units-test/node_modules/convert-units/lib/esm/definitions/all.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

2 import allMeasures from 'convert-units/definitions/all';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/convert-units/lib/cjs/convert.d.ts:37
     1  src/main.ts:2
```

This is because the Typescript compiler is not using the `tsconfig.json` config in that case. Also note that it's not using the `esm` module, it is instead using the `cjs` module which is the default for node environments `node_modules/convert-units/lib/cjs/convert.d.ts:37`.

If you can provide your Typescript config file and details on where you're seeing this error I can help debug :smile:. Better yet, if you can provide a small sample project that I can run on my machine that would be great!

**Comment by skatterwe** [comment]
@Taar thanks for answering.

My tsconfig looks like this:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
  },
  "exclude": ["node_modules", "tmp"]
}

```

I'll create a sample repository

**Comment by skatterwe** [comment]
If i see this correctly the issue is the `moduleResolution: node`.

https://github.com/skatterwe/convert-unit-test

if i change this here to bundler it looks fine

**Comment by skatterwe** [comment]
Just tested in the actual repo. changing the `moduleResolution` fixed. it thanks for answering. closing the ticket
