### ISSUE TITLE
krm and msk have the same singular and plural in description

### ISSUE THREAD

**Issue by hosseintalebi** [convert-units/convert-units#80]
When you call `convert().describe('krm')` it will return:
```
{  
   abbr:"krm",
   measure:"volume",
   system:"metric",
   singular:"Matsked",
   plural:"Matskedar"
}
```
I think the singular (Matsked) and plural (Matskedar) values are for msk and wrongly used for krm.

**Comment by maneetgoyal** [comment]
Noticed that these Swedish units may be wrongly placed **alongside the metric units** inside the `definitions/volume.ts` file.

```
// Swedish units
  krm: {
    name: {
      singular: 'Matsked',
      plural: 'Matskedar',
    },
    to_anchor: 1 / 1000,
  },
  tsk: {
    name: {
      singular: 'Tesked',
      plural: 'Teskedar',
    },
    to_anchor: 5 / 1000,
  },
  msk: {
    name: {
      singular: 'Matsked',
      plural: 'Matskedar',
    },
    to_anchor: 15 / 1000,
  },
  kkp: {
    name: {
      singular: 'Kaffekopp',
      plural: 'Kaffekoppar',
    },
    to_anchor: 150 / 1000,
  },
  glas: {
    name: {
      singular: 'Glas',
      plural: 'Glas',
    },
    to_anchor: 200 / 1000,
  },
  kanna: {
    name: {
      singular: 'Kanna',
      plural: 'Kannor',
    },
    to_anchor: 2.617,
  },
```

Should they be moved to a new system of units instead?

**Comment by maneetgoyal** [comment]
Also should these units to be used via a custom plugin (#194) instead (if they seem less popular)?

**Comment by steakscience** [comment]
krm is not matsked, it should be something else 

see:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/2727095/136140593-e1a8eb67-54ea-4d43-8b51-96ff1a6a6298.png">
