### ISSUE TITLE
[NFR] inches of mercury (inHg)

### ISSUE THREAD

**Issue by ruudboon** [convert-units/convert-units#87]
Would it be possible to add a conversion for inches of mercury (inHg) to this awesome lib?

**Comment by jiminikiz** [comment]
It definitely would be possible. Fork this repo, implement that conversion with a test, and submit a pull request.  Definitely planning on going through the current pull requests ASAP, still 13 outstanding as of writing this.

**Comment by rlueder** [comment]
@ruudboon are you working on a PR for inch of mercury (inHg)? If not I'll send one, as I'd like to add other aviation-related units to the lib:
- feet per minute (ft/min)
- nautical mile (nm or NM)
- pound per hour (lb/h or PPH)

**Comment by ruudboon** [comment]
No, I looked into this but not sure how to implement this. To correctly convert, the temperature should be added as extra parameter
