### ISSUE TITLE
Error in volume conversion

### ISSUE THREAD

**Issue by xploSEoF** [convert-units/convert-units#91]
You've mis-identified "US" values as "imperial".

3.7 litres to the US gallon, whilst 4.5 litres to the imperial gallon. This is quite a big issue.

**Comment by jiminikiz** [comment]
Might be time to explore adding "US values" as another conversion category. Other users of this library have suggested such a feature. Since the library itself explicitly uses "Imperial", it definitely can cause confusion if US values are being used.
